export const SPECIES_TAGS = [
  // Birds
  "Bald Eagle",
  "Great Blue Heron",
  "Red-tailed Hawk",
  "Great Horned Owl",
  "Barn Owl",
  "Mallard Duck",
  "Canada Goose",
  "American Robin",
  "Northern Cardinal",
  "Blue Jay",
  "Downy Woodpecker",
  "American Crow",
  "Black-capped Chickadee",
  "Ruby-throated Hummingbird",
  "Peregrine Falcon",
  "Atlantic Puffin",
  "Kingfisher",
  // Mammals
  "White-tailed Deer",
  "Red Fox",
  "Black Bear",
  "Coyote",
  "Eastern Cottontail",
  "Gray Squirrel",
  "Raccoon",
  "River Otter",
  "American Beaver",
  "Bobcat",
  "Striped Skunk",
  "Mountain Lion",
  "Moose",
  "Gray Wolf",
  // Marine
  "Bottlenose Dolphin",
  "Harbor Seal",
  "Humpback Whale",
  "Loggerhead Sea Turtle",
  "Florida Manatee",
  "Great White Shark",
  "Orca",
  // Reptiles & amphibians
  "Eastern Box Turtle",
  "Common Garter Snake",
  "American Alligator",
  "Green Anole",
  "Painted Turtle",
  "Timber Rattlesnake",
  "Red-eyed Tree Frog",
  // Insects
  "Monarch Butterfly",
  "Bumblebee",
  "Dragonfly",
  "Firefly",
  "Praying Mantis",
  "Luna Moth",
  "Eastern Tiger Swallowtail",
  // Plants & fungi
  "Wild Orchid",
  "Common Sunflower",
  "Venus Flytrap",
  "Wild Rose",
  "Trillium",
  "Fly Agaric Mushroom",
  "Jack-in-the-Pulpit",
] as const;

export type SpeciesTag = (typeof SPECIES_TAGS)[number];
